name: website
on: 
  push: 
    branches:
      - master
    paths:
      - 'website/**'
      - 'website/package.json'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Root Install
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: website
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./website/out
